
def const_data():
    _data = {'Belgium': {'default': [{'year': '1955', 'capture': 'BelgianInventors', 'stamps': ['1.20+30\xa0Fr/C'],
                                      'images': [
                                          'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/TG-s.jpg']},
                                     {'year': '1956', 'capture': 'TheelectricrailroadBruxelles-Luxembourg',
                                      'stamps': ['2Fr'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/TV-s.jpg']},
                                     {'year': '1972', 'capture': 'The50thAnniversaryoftheEisenbahnerUnion',
                                      'stamps': ['7Fr'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/AOR-s.jpg']},
                                     {'year': '1976', 'capture': 'The50thAnniversaryoftheNationalRailroadUnion',
                                      'stamps': ['6.50Fr'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/AUY-s.jpg']},
                                     {'year': '1976', 'capture': 'OpeningoftheBrüsselsMetro', 'stamps': ['6.50Fr'],
                                      'images': [
                                          'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/AUZ-s.jpg']},
                                     {'year': '1983', 'capture': 'HistoricalTramcars', 'stamps': ['7.50Fr', '50Fr'],
                                      'images': [
                                          'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BDN-s.jpg',
                                          'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BDP-s.jpg']},
                                     {'year': '1983', 'capture': 'EUROPAStamps-Inventions', 'stamps': ['20Fr'],
                                      'images': [
                                          'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BDZ-s.jpg']},
                                     {'year': '1985', 'capture': 'NationalTransportationSystem',
                                      'stamps': ['9Fr', '12Fr', '23Fr', '24Fr'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BGN-s.jpg',
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BGO-s.jpg',
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BGP-s.jpg',
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/BGQ-s.jpg']},
                                     {'year': '1998', 'capture': 'Trains', 'stamps': ['17Fr'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/CBL-s.jpg']},
                                     {'year': '2000', 'capture': 'Brussels',
                                      'stamps': ['17/0.42Fr/€', '17/0.42Fr/€', '17/0.42Fr/€', ''], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/2939-b.jpg']},
                                     {'year': '2001', 'capture': 'InternationalStampExhibition"BELGICA´01"',
                                      'stamps': ['17/0.42Fr/€'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/CKU-s.jpg']},
                                     {'year': '2005', 'capture': 'The175thAnniversaryofBelgium-HistoricalEvents',
                                      'stamps': ['0.44€', '0.44€', '0.44€', '0.44€', '0.44€', '0.44€', '0.44€', '0.44€',
                                                 '0.44€', '0.44€', ''], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/3407-b.jpg']},
                                     {'year': '2009', 'capture': 'TheTraininMiniature',
                                      'stamps': ['1Local', '1Local', '1Local', '1Local', '1Local', '1Local', '1Local',
                                                 '1Local', '1Local', '1Local', ''], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/3980-b.jpg']},
                                     {'year': '2010', 'capture': 'The175thAnniversaryoftheBelgianRailways',
                                      'stamps': ['2Local'], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/DVO-s.jpg']},
                                     {'year': '2014', 'capture': 'Trains-OldLocomotives', 'stamps': ['2Local', ''],
                                      'images': [
                                          'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/4462-b.jpg']},
                                     {'year': '2017', 'capture': 'TrainDesign',
                                      'stamps': ['2Local', '2Local', '2Local', '2Local', '2Local', ''], 'images': [
                                         'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Postage-stamps/4716-b.jpg']}],
                         'Railway+parcelpost+stamps': [
                             {'year': '1920', 'capture': 'NewDrawings', 'stamps': ['4Fr', '5Fr'], 'images': []},
                             {'year': '1920', 'capture': 'NewEngravingandNewColors', 'stamps': ['1.40Fr', '10Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/K3-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/K9-s.jpg']},
                             {'year': '1920-1921', 'capture': 'NewColorsandValues', 'stamps': ['1Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/K10-s.jpg']},
                             {'year': '1935', 'capture': 'The100thAnniversaryoftheRailroad',
                              'stamps': ['0.20Fr', '0.30Fr', '0.40Fr', '0.60Fr', '0.80Fr', '0.90Fr', '30Fr', '40Fr',
                                         '50Fr', '100Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/P1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/P2-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/P3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/P5-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/P7-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/P8-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/Q11-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/Q12-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/Q13-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/Q14-s.jpg']},
                             {'year': '1942', 'capture': 'NewDrawings',
                              'stamps': ['9.20Fr', '12.30Fr', '14.30Fr', '100Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/T-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/U-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/V-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/W-s.jpg']},
                             {'year': '1947', 'capture': 'CrossbowwithTrain', 'stamps': ['8Fr', '10Fr', '12Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYA-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYB-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYC-s.jpg']},
                             {'year': '1947', 'capture': 'CrossbowwithTrainOverprinted',
                              'stamps': ['9/8Fr', '11/10Fr', '13.50/12Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYA1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYB1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYC1-s.jpg']},
                             {'year': '1953', 'capture': 'TheOpeningoftheLineBrüsselsNorth-BrüsselsSouth',
                              'stamps': ['200Fr', '200Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AS-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AS1-s.jpg']},
                             {'year': '1953-1956', 'capture': 'TrainStationsinBrüssels',
                              'stamps': ['2Fr', '4Fr', '5Fr', '5Fr', '6Fr', '7Fr', '8Fr', '9Fr', '10Fr', '15Fr', '20Fr',
                                         '80Fr', '100Fr', '200Fr', '300Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT4-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AU-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT5-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT6-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT7-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AT8-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AV-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AU1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AV1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AX-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AX2-s.jpg']},
                             {'year': '1954', 'capture': 'ElectricTrains', 'stamps': ['13Fr', '18Fr', '21Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYR-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYS-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYT-s.jpg']},
                             {'year': '1954', 'capture': 'ElectricTrains-Overprinted', 'stamps': ['19/18Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YYV-s.jpg']},
                             {'year': '1959', 'capture': 'OldNorthStationinBrussels', 'stamps': ['20Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZC-s.jpg']},
                             {'year': '1960', 'capture': 'The75AnniversaryoftheNationalRailway',
                              'stamps': ['20Fr', '50Fr', '60Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AY-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AY1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AY2-s.jpg']},
                             {'year': '1960', 'capture': 'The75AnniversaryoftheNationalRailway', 'stamps': ['70Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AY3-s.jpg']},
                             {'year': '1962', 'capture': 'SouthStationinBrussels', 'stamps': ['24Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZD-s.jpg']},
                             {'year': '1963', 'capture': 'SouthStationinBrussels-Overprinted', 'stamps': ['26/24Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZE-s.jpg']},
                             {'year': '1963', 'capture': 'CentralStationinAntwerp', 'stamps': ['26Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZF-s.jpg']},
                             {'year': '1964', 'capture': 'CentralStationinAntwerp-Overprinted', 'stamps': ['28/26Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZG-s.jpg']},
                             {'year': '1965', 'capture': "St.Peter'sStationinGhent", 'stamps': ['28Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZH-s.jpg']},
                             {'year': '1966', 'capture': "St.Peter'sStationinGhent-Overprinted", 'stamps': ['35/28Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/YZI-s.jpg']},
                             {'year': '1967', 'capture': 'ArlonRailroadStation', 'stamps': ['25Fr', '30Fr', '35Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/UZJ-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/UZK-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/UZL-s.jpg']},
                             {'year': '1968', 'capture': 'Locomotive',
                              'stamps': ['1Fr', '2Fr', '3Fr', '4Fr', '5Fr', '6Fr', '7Fr', '8Fr', '9Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ2-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ4-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ5-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ6-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ7-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AZ8-s.jpg']},
                             {'year': '1968', 'capture': 'Locomotives', 'stamps': ['10Fr', '20Fr', '30Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BA-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BA1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BA2-s.jpg']},
                             {'year': '1968', 'capture': 'Locomotives', 'stamps': ['60Fr', '80Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BB1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BB2-s.jpg']},
                             {'year': '1968', 'capture': 'Locomotives', 'stamps': ['200Fr', '300Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BC1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BC2-s.jpg']},
                             {'year': '1968', 'capture': 'Locomotive', 'stamps': ['500Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BD-s.jpg']},
                             {'year': '1972-1973', 'capture': 'NewValues', 'stamps': ['70Fr', '90Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BB3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BB4-s.jpg']},
                             {'year': '1975', 'capture': 'NewValues', 'stamps': ['20Fr', '50Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AU4-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/AU5-s.jpg']},
                             {'year': '1980', 'capture': 'GoodsWagons',
                              'stamps': ['1Fr', '2Fr', '3Fr', '4Fr', '5Fr', '6Fr', '7Fr', '8Fr', '9Fr', '10Fr', '20Fr',
                                         '30Fr', '40Fr', '50Fr', '60Fr', '70Fr', '80Fr', '90Fr', '100Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI2-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI4-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI5-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI6-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI7-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BI8-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BJ-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BJ1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BJ2-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BJ3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BK-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BK1-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BK2-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BK3-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BK4-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BL-s.jpg']},
                             {'year': '1980', 'capture': 'GoodsWagons', 'stamps': ['200Fr', '300Fr', '500Fr'],
                              'images': [
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BL1-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BL2-s.jpg',
                                  'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BL3-s.jpg']},
                             {'year': '1985', 'capture': 'The150thAnniversaryoftheNationalRailway',
                              'stamps': ['250Fr', '500Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BN-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BO-s.jpg']},
                             {'year': '1996', 'capture': 'TheOpeningoftheParis-Brüssels-AmsterdamLine',
                              'stamps': ['100Fr', '300Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BQ-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BR-s.jpg']},
                             {'year': '1997', 'capture': 'ModernizationoftheNationalRailroad',
                              'stamps': ['50Fr', '100Fr', '200Fr'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BS-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BT-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BU-s.jpg']},
                             {'year': '1998', 'capture': '"Eurostar"and"Thalys"',
                              'stamps': ['80/2Fr/€', '80/2Fr/€', '160/4Fr/€'], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BV-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BW-s.jpg',
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/BX-s.jpg']},
                             {'year': '2000', 'capture': 'FreightTraffic',
                              'stamps': ['20/0.50Fr/€', '30/0.74Fr/€', '50/1.24Fr/€', '150/3.72Fr/€', ''], 'images': [
                                 'https://swmedia-4cd6.kxcdn.com/media/catalogue/Belgium/Railway-parcelpost-stamps/0445-b.jpg']}]},
             'Austria': {'default': [
                 {'year': '1937', 'capture': 'The100thAnniversaryofAustrianRailroads', 'stamps': ['12G', '25G'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/GZ-s.jpg',
                             'https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/HA-s.jpg']},
                 {'year': '1948', 'capture': 'RebuildingAustria', 'stamps': ['30+10\xa0G'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/OC-s.jpg']},
                 {'year': '1978', 'capture': 'ViennaSubway', 'stamps': ['3S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/APP-s.jpg']},
                 {'year': '1979', 'capture': 'The100thAnniversaryoftheRaab-Ödenburg-EbenfurterRailway',
                  'stamps': ['2.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/ARX-s.jpg']},
                 {'year': '1982', 'capture': 'EUROPAStamps-HistoricEvents', 'stamps': ['6S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/AVF-s.jpg']},
                 {'year': '1984', 'capture': 'RailwayAnniversaries', 'stamps': ['3.50S', '4.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/AYA-s.jpg',
                             'https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/AYB-s.jpg']},
                 {'year': '1986', 'capture': 'The100thAnniversaryoftheSalzburgRegionalTrains', 'stamps': ['4S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BAQ-s.jpg']},
                 {'year': '1987', 'capture': "The150thAnniversaryofAustria'sRailroad", 'stamps': ['6S', ''],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/1931-b.jpg']},
                 {'year': '1988', 'capture': 'The100thAnniversaryoftheMühlkreisRailway', 'stamps': ['4S', '5S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BDA-s.jpg',
                             'https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BDB-s.jpg']},
                 {'year': '1989', 'capture': 'The100thAnniversaryoftheAchenseeRailway', 'stamps': ['5S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BEU-s.jpg']},
                 {'year': '1993', 'capture': 'The100thAnniversaryofSchafbergMountainSteamTrain', 'stamps': ['6S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BKG-s.jpg']},
                 {'year': '1994', 'capture': 'The100thAnniversaryoftheMurtalRailroad', 'stamps': ['6S', '5.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BLI-s.jpg',
                             'https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BLJ-s.jpg']},
                 {'year': '1997', 'capture': 'Railroads', 'stamps': ['6S', '7.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BPK-s.jpg',
                             'https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BPL-s.jpg']},
                 {'year': '1998', 'capture': 'Railroads', 'stamps': ['6.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BQQ-s.jpg']},
                 {'year': '1998', 'capture': 'Railroads', 'stamps': ['6.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BQU-s.jpg']},
                 {'year': '1998', 'capture': 'Railroads', 'stamps': ['6.50S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BQX-s.jpg']},
                 {'year': '2001', 'capture': 'The100thAnniversaryofZilltertalRailway', 'stamps': ['7S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BUR-s.jpg']},
                 {'year': '2001', 'capture': 'Four-trackRailways', 'stamps': ['7S'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BVG-s.jpg']},
                 {'year': '2002', 'capture': 'Locomotive', 'stamps': ['0.51€'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BWY-s.jpg']},
                 {'year': '2003', 'capture': 'Locomotive', 'stamps': ['0.75€'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/BYD-s.jpg']},
                 {'year': '2004', 'capture': 'Locomotive', 'stamps': ['55(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CAR-s.jpg']},
                 {'year': '2005', 'capture': 'Locomotive', 'stamps': ['55(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CHQ-s.jpg']},
                 {'year': '2006', 'capture': 'Locomotive', 'stamps': ['55(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CJS-s.jpg']},
                 {'year': '2007', 'capture': 'Locomotive', 'stamps': ['55(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CLY-s.jpg']},
                 {'year': '2007', 'capture': 'Locomotive', 'stamps': ['75(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CMM-s.jpg']},
                 {'year': '2008', 'capture': 'Locomotive', 'stamps': ['75(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CPP-s.jpg']},
                 {'year': '2008', 'capture': 'EmpressElizabethWesternRailway', 'stamps': ['100(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CPW-s.jpg']},
                 {'year': '2009', 'capture': 'The100thAnniversaryoftheWachauRailway', 'stamps': ['75(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CSE-s.jpg']},
                 {'year': '2009', 'capture': 'Locomotive', 'stamps': ['100(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CST-s.jpg']},
                 {'year': '2010', 'capture': 'Train-Kleinbahn', 'stamps': ['55(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CTR-s.jpg']},
                 {'year': '2010', 'capture': 'The150thAnniversaryofGrafKoflachRailway', 'stamps': ['1.00€'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CTX-s.jpg']},
                 {'year': '2010', 'capture': 'TheMendelRailway', 'stamps': ['65(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CUA-s.jpg']},
                 {'year': '2010', 'capture': 'The125thAnniversaryoftheFrontierRailwaySpielfeldStrass-BadRadkersburg',
                  'stamps': ['65(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CUS-s.jpg']},
                 {'year': '2010', 'capture': 'StampDay-AustrianRailwaysRailjet', 'stamps': ['2.65+1.30\xa0€'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CUX-s.jpg']},
                 {'year': '2010', 'capture': 'The100thAnniversaryoftheWechselRailway', 'stamps': ['1.00€'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CVC-s.jpg']},
                 {'year': '2011', 'capture': 'The150thAnniversaryoftheBirthofKarlGölsdorf,1861-1916',
                  'stamps': ['65(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CWA-s.jpg']},
                 {'year': '2011', 'capture': 'The175thAnniversaryoftheBudweis-Linz-Gmunden', 'stamps': ['62(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CWG-s.jpg']},
                 {'year': '2011', 'capture': 'DayoftheStamp', 'stamps': ['272+136\xa0(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CWU-s.jpg']},
                 {'year': '2011', 'capture': 'Transporation-The120thAnniversaryoftheErzbergRailway',
                  'stamps': ['90(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CXN-s.jpg']},
                 {'year': '2012', 'capture': 'Trains-DayoftheStamp', 'stamps': ['272+136\xa0(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CYX-s.jpg']},
                 {'year': '2012', 'capture': 'OldAustria', 'stamps': ['70(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CZK-s.jpg']},
                 {'year': '2012', 'capture': 'The100thAnniversaryoftheMittenwaldRailway', 'stamps': ['145(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/CZU-s.jpg']},
                 {'year': '2012',
                  'capture': 'The140thAnniversaryoftheGrantingofConcessionforRaab-Oedenburg-EbenfurterRailway',
                  'stamps': ['62(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DAE-s.jpg']},
                 {'year': '2012', 'capture': 'Locomotives-The175thAnniversaryofRailwayinAustria', 'stamps': ['90(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DAM-s.jpg']},
                 {'year': '2013', 'capture': 'BadenTrainStationDuringtheBiedermeierPeriod', 'stamps': ['145(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DBA-s.jpg']},
                 {'year': '2013', 'capture': 'The130thAnniversaryoftheDeathofJuliusLatt,', 'stamps': ['70(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DBK-s.jpg']},
                 {'year': '2013', 'capture': 'The100thAnniversaryoftheAusserfernRailway', 'stamps': ['70(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DCG-s.jpg']},
                 {'year': '2013', 'capture': 'DayoftheStamp', 'stamps': ['282+141\xa0(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DCH-s.jpg']},
                 {'year': '2014', 'capture': 'The125thAnniversaryoftheSteyrValleyRailway', 'stamps': ['145(C)', ''],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/3193-b.jpg']},
                 {'year': '2014', 'capture': 'OpeningoftheViennaCentralStation', 'stamps': ['90(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DFD-s.jpg']},
                 {'year': '2015', 'capture': 'The160thAnniversaryoftheSemmeringRailway', 'stamps': ['160(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DHV-s.jpg']},
                 {'year': '2016', 'capture': 'Trains-GleichenbergRailway', 'stamps': ['170(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DJX-s.jpg']},
                 {'year': '2016', 'capture': 'StampDay', 'stamps': ['288+144\xa0(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DKD-s.jpg']},
                 {'year': '2017', 'capture': 'The125thAnniversaryoftheStainzRailway', 'stamps': ['125(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DMD-s.jpg']},
                 {'year': '2017', 'capture': 'The150thAnniversaryoftheBrennerRailway', 'stamps': ['175(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DMI-s.jpg']},
                 {'year': '2018', 'capture': 'Trains-The150thAnniversaryoftheKronprinzRudolf-Bahn',
                  'stamps': ['135(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DPG-s.jpg']},
                 {'year': '2019', 'capture': 'MariazellRailway-Himmelstreppe', 'stamps': ['230(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DRF-s.jpg']},
                 {'year': '2020', 'capture': 'Trains-RailwayClassVT10', 'stamps': ['230(C)'],
                  'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Austria/Postage-stamps/DTA-s.jpg']}],
                         'Railway+parcelpost+stamps': None}, 'Poland': {'default': [
            {'year': '1948', 'capture': 'EuropeanRailwaySchedulingConference,Kraków', 'stamps': ['18Zł'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/JM-s.jpg']},
            {'year': '1954', 'capture': 'TheDevelopmentofElectricRailways', 'stamps': ['60Gr', '80Gr'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/QN-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/QO-s.jpg']},
            {'year': '1954', 'capture': 'TheDayoftheRailways', 'stamps': ['40Gr'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/RS-s.jpg']},
            {'year': '1976', 'capture': 'TheHistoryofLocomotives',
             'stamps': ['50Gr', '1Zł', '1.50Zł', '1.50Zł', '2.70Zł', '4.50Zł', '4.90Zł'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXR-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXS-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXT-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXU-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXV-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXX-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/BXY-s.jpg']},
            {'year': '1995', 'capture': 'The150thAnniversaryofPolishRailways', 'stamps': ['35Gr', '60Gr', '80Gr'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/DNL-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/DNM-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/DNN-s.jpg']},
            {'year': '2018', 'capture': 'Trains-The100thAnniversaryoftheKędzierzyn-KoźleSteamLocomotivePlant',
             'stamps': ['2.60Zł', '3.20Zł', ''],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/HZE-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/Poland/Postage-stamps/HZF-s.jpg']}],
                                                                        'Railway+parcelpost+stamps': None}, 'Russia': {
            'default': [{'year': '1922', 'capture': 'CharityforHungerVictims', 'stamps': ['R'],
                         'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/Russia/Postage-stamps/BV-s.jpg']},
                        {'year': '2018', 'capture': 'MonumentalArtoftheMoscowMetro',
                         'stamps': ['40₽', '40₽', '40₽', '40₽', ''], 'images': [
                            'https://swmedia-4cd6.kxcdn.com/media/catalogue/Russia/Postage-stamps/2611-b.jpg']}],
            'Railway+parcelpost+stamps': None}, 'USSR': {'default': [
            {'year': '1946', 'capture': 'FiveYearReconstructionPlan', 'stamps': ['15K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/ZW-s.jpg']},
            {'year': '1948', 'capture': 'Five-YearPlaninFourYear', 'stamps': ['60K', '1R'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/AHQ-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/AHR-s.jpg']},
            {'year': '1958', 'capture': '2203-2213.100летрусскойпочтовоймарке', 'stamps': ['60K', '1R'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/BOJ-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/BOL-s.jpg']},
            {'year': '1958', 'capture': 'The100thAnniversaryoftheRussianPostageStamp',
             'stamps': ['40K', '60K', '60K', '1R', '1R', ''],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/1917-b.jpg']},
            {'year': '1962', 'capture': 'Resolutionof22ndCommunistPartyCongress', 'stamps': ['4K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/CKP-s.jpg']},
            {'year': '1965', 'capture': 'MaterialandTechnicalBaseofCommunism', 'stamps': ['12K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/DAA-s.jpg']},
            {'year': '1965', 'capture': 'HistoryoftheRussianPostOffice', 'stamps': ['2K', '6K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/DCK-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/DCL-s.jpg']},
            {'year': '1967', 'capture': 'The50thAnniversaryofSocialism', 'stamps': ['4K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/DMX-s.jpg']},
            {'year': '1968', 'capture': 'SovietRailways', 'stamps': ['4K', '10K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/DSE-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/DSF-s.jpg']},
            {'year': '1974', 'capture': 'The100thAnniversaryofYegorovRailwayWagonWorks', 'stamps': ['4K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/ESC-s.jpg']},
            {'year': '1981', 'capture': 'Resolutionsof26thCommunistPartyCongress', 'stamps': ['4K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/FYV-s.jpg']},
            {'year': '1984', 'capture': 'CompletionofBaikal-AmurRailway', 'stamps': ['5K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/GMM-s.jpg']},
            {'year': '1986', 'capture': 'SteamLocomotives-Monuments', 'stamps': ['10K', '20K', '30K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/GUE-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/GUF-s.jpg',
                        'https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/GUG-s.jpg']},
            {'year': '1991', 'capture': 'Стандартныйвыпуск', 'stamps': ['7K'],
             'images': ['https://swmedia-4cd6.kxcdn.com/media/catalogue/USSR/Postage-stamps/HOL-s.jpg']}],
                                                         'Railway+parcelpost+stamps': None}}
    return _data
